version: "3"

# TODO: separate template for price-scrappers
# TODO: minified envar file

services:

  price_scrapper_0:
    build:
      context: btcmon-price-scrapper/
      dockerfile: Dockerfile
    depends_on:
      - db_service
      - config
    links:
      - db_service:db_service
      - config:config
    environment:
      - PUT_HOST=db_service
      - PUT_PORT=8080
      - DATASET=0
      - INTERVAL=1
      - CONFIG_HOST=config
      - CONFIG_PORT=8080
    tty: true

  price_scrapper_1:
    build:
      context: btcmon-price-scrapper/
      dockerfile: Dockerfile
    depends_on:
      - db_service
      - config
    links:
      - db_service:db_service
      - config:config
    environment:
      - PUT_HOST=db_service
      - PUT_PORT=8080
      - DATASET=1
      - INTERVAL=1
      - CONFIG_HOST=config
      - CONFIG_PORT=8080
    tty: true

  db_service:
    build:
      context: btcmon-db-service/
      dockerfile: Dockerfile
    depends_on:
      - db
      - config
    ports:
      - "8080:8080"
    links:
      - db:db
      - config:config
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - DB_NAME=btcmon
      - DB_HOST=db
      - CONFIG_HOST=config
      - CONFIG_PORT=8080
    tty: true

  config:
    build:
      context: btcmon-config/
      dockerfile: Dockerfile
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
    tty: true

  db:
    build:
      context: .
      dockerfile: db_Dockerfile
    tty: true
