version: "3"

services:

  price_scrapper_0:
    build:
      context: btcmon-price-scrapper/
      dockerfile: Dockerfile
    depends_on:
      - db_service
      - config
    environment:
      - DATASET=0
      - INTERVAL=1
    env_file:
      - ./global-variables.env
    tty: true

  price_scrapper_1:
    build:
      context: btcmon-price-scrapper/
      dockerfile: Dockerfile
    depends_on:
      - db_service
      - config
    environment:
      - DATASET=1
      - INTERVAL=1
    env_file:
      - ./global-variables.env
    tty: true

  db_service:
    build:
      context: btcmon-db-service/
      dockerfile: Dockerfile
    depends_on:
      - db
      - config
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=btcmon
      - DB_HOST=db
    env_file:
      - ./global-variables.env
    tty: true

  config:
    build:
      context: btcmon-config/
      dockerfile: Dockerfile
    env_file:
      - ./global-variables.env
    tty: true

  db:
    build:
      context: .
      dockerfile: db_Dockerfile
    tty: true
